[project]
name = "url_ai_checker"
version = "0.1.0"
description = "LibrerÃ­a con IA para revisar URLs."
authors = [{name="Autor"}]
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
dependencies = ["requests", "scikit-learn", "numpy", "networkx"]
